services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb

volumes:
  mongodb-data:
  mongodb-configdb:
