name: Release new version

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release and tag version  (ie 1.5.0)'
        required: true
      developmentVersion:
        description: 'Next development version, with SNAPSHOT'
        required: true

jobs:
  release_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set release version in pom.xml
      shell: bash -l {0}
      run: |
        mvn versions:set-property -Dproperty=revision -DnewVersion=${{ github.event.inputs.releaseVersion }}
  
    - name: Build and upload artifacts to nexus
      shell: bash -l {0}
      run: |
        mvn --version
        mvn -Dmaven.repo.local=${{ github.workspace}}/.m2/repository -P prod,default -DskipTests clean deploy
        git add pom.xml
        git commit -m "Release ${{ github.event.inputs.releaseVersion }}"
        git push

    - name: Tag the project
      shell: bash -l {0}
      run: |
        git tag ${{ github.event.inputs.releaseVersion }} -m "Release ${{ github.event.inputs.releaseVersion }}"
        git push origin ${{ github.event.inputs.releaseVersion }}

    - name: Bump up version in branch to next development version
      shell: bash -l {0}
      run: |
        mvn versions:set-property -Dproperty=revision -DnewVersion=${{ github.event.inputs.developmentVersion }} 
        git add pom.xml
        git commit -m "Next development version is ${{ github.event.inputs.developmentVersion }}"
        git push

    - name: Create A Pull Request
      uses: thomaseizinger/create-pull-request@1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        head: master
        base: develop
        title: Released master into develop
        body: |
          Hi!
          This PR was created in response workflow running.
          I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.